import type { PostRow } from "@/types";

export function makePost(overrides: Partial<PostRow> = {}): PostRow {
  const base: PostRow = {
    id: "abc123",
    name: "t3_abc123",
    kind: "t3",
    content_origin: "saved",
    title: "Example post",
    author: "alice",
    subreddit: "typescript",
    permalink: "/r/typescript/comments/abc123/example_post/",
    url: "https://example.com/article",
    domain: "example.com",
    selftext: null,
    body: null,
    score: 123,
    created_utc: Math.floor(Date.now() / 1000) - 3600,
    num_comments: 42,
    upvote_ratio: 0.92,
    is_self: 0,
    over_18: 0,
    is_video: 0,
    is_gallery: 0,
    post_hint: null,
    link_flair_text: null,
    thumbnail: null,
    preview_url: null,
    parent_id: null,
    link_id: null,
    link_title: null,
    link_permalink: null,
    is_submitter: 0,
    distinguished: null,
    edited: null,
    stickied: 0,
    spoiler: 0,
    locked: 0,
    archived: 0,
    fetched_at: Date.now(),
    updated_at: Date.now(),
    is_on_reddit: 1,
    last_seen_at: Date.now(),
    raw_json: "{}",
    tags: null,
  };
  return { ...base, ...overrides };
}
