#!/usr/bin/env bun
/**
 * Codegen for single-binary distribution: reads packages/web/dist (a vite
 * build) and generates gitignored modules that embed every dist file into the
 * compiled binary via Bun's `with { type: "file" }` imports:
 *
 * - src/web-assets.generated.ts   one import per dist file + a manifest of
 *                                 request pathname → embedded file reference
 * - src/index.binary.generated.ts binary entry: registers the manifest in
 *                                 src/web-assets.ts, then boots src/index.ts
 *
 * Run via `bun run build:binary`; plain `bun run build` compiles src/index.ts
 * directly and keeps the committed empty-manifest fallback.
 */
import { existsSync, readdirSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";

/**
 * Dist-relative POSIX paths of every file under distDir, sorted. Sourcemaps
 * (vite builds with `sourcemap: true` for dev debugging) are excluded — the
 * ~2.4MB map would otherwise dominate every compiled binary and npm package.
 */
export function listDistFiles(distDir: string, prefix = ""): string[] {
  const files: string[] = [];
  for (const entry of readdirSync(join(distDir, prefix), { withFileTypes: true })) {
    const relPath = prefix === "" ? entry.name : `${prefix}/${entry.name}`;
    if (entry.isDirectory()) {
      files.push(...listDistFiles(distDir, relPath));
    } else if (entry.isFile() && !entry.name.endsWith(".map")) {
      files.push(relPath);
    }
  }
  return files.sort();
}

/** Module text embedding `files` (dist-relative paths) via `importPrefix`. */
export function generateManifestModule(files: string[], importPrefix: string): string {
  const imports = files.map(
    (file, i) => `import asset_${i} from "${importPrefix}/${file}" with { type: "file" };`,
  );
  // bun-types declares some extensions (e.g. *.html) with non-string module
  // types for attribute-less imports; `with { type: "file" }` always yields a
  // path string at runtime, so cast each reference.
  const entries = files.map((file, i) => `  "/${file}": asset_${i} as unknown as string,`);
  return [
    "// Generated by scripts/embed-web-assets.ts — do not edit (gitignored).",
    'import type { AssetManifest } from "./web-assets";',
    "",
    ...imports,
    "",
    "export const manifest: AssetManifest = {",
    ...entries,
    "};",
    "",
  ].join("\n");
}

export function generateBinaryEntryModule(): string {
  return [
    "// Generated by scripts/embed-web-assets.ts — do not edit (gitignored).",
    'import { setEmbeddedAssets } from "./web-assets";',
    'import { manifest } from "./web-assets.generated";',
    "",
    "setEmbeddedAssets(manifest);",
    'await import("./index");',
    "",
  ].join("\n");
}

if (import.meta.main) {
  const distDir = resolve(import.meta.dir, "../../web/dist");
  if (!existsSync(join(distDir, "index.html"))) {
    console.error(
      `[embed-web-assets] no web build at ${distDir} — run 'bun run --filter @reddit-cached/web build' first.`,
    );
    process.exit(1);
  }

  const files = listDistFiles(distDir);
  const srcDir = resolve(import.meta.dir, "../src");
  writeFileSync(
    join(srcDir, "web-assets.generated.ts"),
    generateManifestModule(files, "../../web/dist"),
  );
  writeFileSync(join(srcDir, "index.binary.generated.ts"), generateBinaryEntryModule());
  console.error(`[embed-web-assets] embedded ${files.length} dist files`);
}
