#!/usr/bin/env bun
/**
 * npm packaging: stages a publishable "reddit-cached" package in repo-root
 * dist-npm/pkg (gitignored). The workspace packages are never published —
 * this generated output is.
 *
 *   bun run packages/cli/scripts/package-npm.ts
 *   cd dist-npm/pkg && npm publish
 *
 * The bin is a single `bun build --target=bun` bundle (workspace deps
 * inlined, bun:* builtins external), so the installed package needs Bun at
 * runtime (bun:sqlite) but nothing else. The web dashboard ships as plain
 * files under web-dist/; a generated entry registers them in the embedded
 * asset manifest with paths resolved relative to the installed bundle at
 * runtime — `bun build` asset imports are cwd-relative and would break, so
 * type:file embedding is deliberately not used here.
 */
import { cpSync, existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { join, resolve } from "node:path";
import { listDistFiles } from "./embed-web-assets";

const cliDir = resolve(import.meta.dir, "..");
const rootDir = resolve(cliDir, "../..");
const webDistDir = join(rootDir, "packages/web/dist");
const pkgDir = join(rootDir, "dist-npm/pkg");

function run(cmd: string[], cwd: string): void {
  // NODE_ENV=production for the same reason as build-binary.ts: `bun build`
  // inlines process.env.NODE_ENV reads into the bundle, and serve's
  // CSP/logging profile keys off it.
  const proc = Bun.spawnSync(cmd, {
    cwd,
    env: { ...process.env, NODE_ENV: "production" },
    stdout: "inherit",
    stderr: "inherit",
  });
  if (proc.exitCode !== 0) {
    process.exit(proc.exitCode ?? 1);
  }
}

const version = (
  JSON.parse(readFileSync(join(cliDir, "package.json"), "utf8")) as { version: string }
).version;

// --- web dashboard build (served by `reddit-cached serve`) ---
if (!existsSync(join(webDistDir, "index.html"))) {
  run(["bun", "run", "--filter", "@reddit-cached/web", "build"], rootDir);
}

rmSync(join(rootDir, "dist-npm"), { recursive: true, force: true });
mkdirSync(join(pkgDir, "bin"), { recursive: true });

// --- generated entry: register web-dist assets, then boot the CLI ---
// Mirrors index.binary.generated.ts, but resolves asset paths at runtime
// relative to the installed bundle (bin/../web-dist) instead of embedding.
const files = listDistFiles(webDistDir);
const manifestEntries = files.map((file) => `  "/${file}": join(base, "${file}"),`);
const npmEntry = [
  "// Generated by scripts/package-npm.ts — do not edit (gitignored).",
  'import { join } from "node:path";',
  'import { setEmbeddedAssets } from "./web-assets";',
  "",
  "// import.meta.dir is the installed package's bin/ directory at runtime",
  "// (Bun resolves the node_modules/.bin symlink to the real file).",
  'const base = join(import.meta.dir, "..", "web-dist");',
  "setEmbeddedAssets({",
  ...manifestEntries,
  "});",
  'await import("./index");',
  "",
].join("\n");
writeFileSync(join(cliDir, "src/index.npm.generated.ts"), npmEntry);

// --- bundle the CLI (single JS file; bun:* stay external) ---
run(
  [
    "bun",
    "build",
    "./src/index.npm.generated.ts",
    "--target=bun",
    `--outfile=${join(pkgDir, "bin/reddit-cached.js")}`,
  ],
  cliDir,
);

// npm bin shims and direct execution both honor the shebang; `bun build`
// emits its `// @bun` pragma first, which still applies after a shebang line.
const binPath = join(pkgDir, "bin/reddit-cached.js");
writeFileSync(binPath, `#!/usr/bin/env bun\n${readFileSync(binPath, "utf8")}`);

// --- static assets + docs ---
// Skip sourcemaps to match listDistFiles above (they never reach the served
// asset manifest and would triple the package size).
cpSync(webDistDir, join(pkgDir, "web-dist"), {
  recursive: true,
  filter: (src) => !src.endsWith(".map"),
});
cpSync(join(rootDir, "README.md"), join(pkgDir, "README.md"));
cpSync(join(rootDir, "LICENSE"), join(pkgDir, "LICENSE"));

writeFileSync(
  join(pkgDir, "package.json"),
  `${JSON.stringify(
    {
      name: "reddit-cached",
      version,
      description:
        "Local-first archive of your Reddit saved, upvoted, and posted content — SQLite cache, web dashboard, and JSON-first CLI. Requires Bun (bun:sqlite).",
      license: "MIT",
      homepage: "https://github.com/aurokin/reddit_cached",
      repository: { type: "git", url: "git+https://github.com/aurokin/reddit_cached.git" },
      type: "module",
      bin: { "reddit-cached": "bin/reddit-cached.js" },
      files: ["bin", "web-dist", "README.md", "LICENSE"],
      engines: { bun: ">=1.2.0" },
    },
    null,
    2,
  )}\n`,
);

console.error(`package-npm: staged reddit-cached@${version} in ${pkgDir}`);
